server:
    port: 8052

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/WALLET?autoReconnect=true&useSSL=false
        username: root
        password: root@123

    jpa:
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update

#permissao-service:
#    url: https://user-info.herokuapp.com
